version: '3.8'
services:
  cnmysql:
    container_name: cnmysql
    image: mysql:8
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - 3307:3306
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION',
      ]
    cap_add:
      - SYS_NICE
  app_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /app
    env_file:
      - .env
    working_dir: /app
    command: npm run start:dev -- --debug 0.0.0.0:9111
    ports:
      - '${API_PORT}:${API_PORT}'
      - '9111:9111'
    environment:
      - NODE_ENV=${NODE_ENV}
